#!/usr/bin/php
<?php

/*

Created by John Lokerse on 20-04-2013.
Version 1.3

*/

$array = array();
$i = 1;

// Counts passed arguments and adds it into an array.
while ( $i < $argc ) {
	array_push($array, $argv[$i]);
	$i++;
}

// Makes a string with delimeter '+' and passes it into $arg.
$arg = implode("+", $array);

// Function with the imploded argument (for example 'Jack+Reacher').
function my_movinfo ($arg) {

	// Decodes the JSON IMDB API with the passed argument (for example 'http://imdbapi.org/?title=Jack+Reacher').
	$decode=json_decode(file_get_contents('http://imdbapi.org/?title=' . $arg));
	
	if ( ! is_array($decode) ) {
		if ( $decode->code == 501 ){
			echo "I need a movie title to check. Please do MovieInfo <title>.\n";
		} else {
			echo "\n-----------------------";
			echo "\n- " . $decode->code . ": " . $decode->error . " -\n";
			echo "-----------------------\n\n";
		}
	} else {
		foreach ($decode as $key=>$value)
		{
			echo "-----";
			echo "\n Title: \n" . $value->title . "\n-";
			echo "\n Plot: \n" . $value->plot_simple . "\n-";
			echo "\n Genres: \n" . implode(", " , $value->genres) . "\n";
			echo "----- \n";
		}
	}		
}

// Executes function.
my_movinfo($arg);


?>